### ISSUE TITLE
Documentation request: Removal of styleguide

### ISSUE THREAD

**Issue by jdarrohn** [KaiHotz/react-rollup-boilerplate#13]
First off 👍 on this package, it does exactly what I need and then some. Works great with Material UI right out of the box.  With that said, I would like to perhaps be able to remove the styleguide, as , in my case, I am going to use Storybook. Here is what I came up with as a checklist:

1. Remove the `styleguide` directory from the root
2. Remove the `styleguide:build`,`predeploy`, and `deploy` scripts from `package.json`
3. Remove `gh-pages` and `react-styleguidist` as a depedency in `package.json`

**Comment by jdarrohn** [comment]
Can I perhaps remove `webpack.json` too from `config`?

**Comment by KaiHotz** [comment]
@jdarrohn Yes this is exactly what you need to remove the ```styleguide``` from it.
You might want to keep ```webpack.js``` due to I believe that ```storybook``` also needs a ```webpack.js``` file to run.
