### ISSUE TITLE
Descriptions on props 

### ISSUE THREAD

**Issue by AnthonyCrowcroft** [KaiHotz/react-rollup-boilerplate#14]
Hey, just wanted to say great work as this helped extensively for getting styleguidist working in our project but i was wondering if you'd be able to get an example of how to best add descriptions to the props for any component, seen a few examples where they comment in the interface but not sure the best way forward.

**Comment by AnthonyCrowcroft** [comment]
Nevermind figured it out.

**Comment by KaiHotz** [comment]
@AnthonyCrowcroft Awesome, I'm glad my repo is of use for you and that you could figure out the comments on the props.
Maybe just leave a short comment here on what you did, so it can be a reference for other devs in the future.

Thanks.

**Comment by AnthonyCrowcroft** [comment]
I honestly went with using the comment technique described above.
`  /** The value to be displayed in the input element */`
placing  a comment like the above for each prop in the interface filled out the table beautifully :)
