### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by Deep-Codes** [KaiHotz/react-rollup-boilerplate#16]
Hey Fantastic Boilerplate, I had an issue which I solved I will place it here so that People can Solve it if they get Stuck.

Steps to Reproduce:

```sh
git clone git@github.com:KaiHotz/react-rollup-boilerplate.git
cd react-rollup-boilerplate
npm install or yarn
yarn start
```
Error Message at `http://localhost:6060/`

<img width="1205" alt="Screenshot 2021-02-16 at 7 23 12 PM" src="https://user-images.githubusercontent.com/61158210/108072039-6b212a00-708c-11eb-8020-ad9d8ca2111f.png">

FIX for this:

```sh
yarn add -D process
```

Add Process Plugin to `webpack.config.js`

```js
  plugins: [
    new webpack.ProvidePlugin({
      process: 'process/browser',
    }),
  ],
```

So complete `webpack.config.js` file:

```js
// Webpack configuration
const webpack = require('webpack');

module.exports = {
  module: {
    rules: [
      { test: /\.tsx?$/, loader: 'ts-loader' },
      { enforce: 'pre', test: /\.js$/, loader: 'source-map-loader' },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
      {
        test: /\.(s?)css$/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
      },
      {
        test: /\.(png|jpg|jpeg|webp|gif)$/,
        use: ['url-loader'],
      },
      {
        test: /\.svg$/,
        use: [
          {
            loader: '@svgr/webpack',
          },
        ],
      },
    ],
  },
  devtool: 'source-map',
  resolve: { extensions: ['.ts', '.tsx', '.js', '.jsx', '.json'] },
  plugins: [
    new webpack.ProvidePlugin({
      process: 'process/browser',
    }),
  ],
};

```

Solved!

<img width="1432" alt="Screenshot 2021-02-16 at 7 26 37 PM" src="https://user-images.githubusercontent.com/61158210/108072442-ea166280-708c-11eb-8d61-9cad87b1ee5f.png">

**Comment by Deep-Codes** [comment]
Hope this Helps 👍🏽

**Comment by KaiHotz** [comment]
@Deep-Codes thanks for the PR and the Fix, PR got approved and merged. 
Had to do a bit of cleanup since there was a package-lock and yarn.lock file. 
I'm glad you liked it and also thankful for your contribution.
