### ISSUE TITLE
Rollup how to deal with Less or css to a separate module folder

### ISSUE THREAD

**Issue by dalongjason** [KaiHotz/react-rollup-boilerplate#35]
## project structure
｜-components
｜｜-components1 
｜｜|-- index.less
｜｜|-- index.js
｜｜-components1
｜｜|-- index.less
｜｜|-- index.js
｜-index.js
｜- index.less

## output
｜-components
｜｜-components1 
｜｜|-- index.css
｜｜|-- index.js
｜｜-components1
｜｜|-- index.css
｜｜|-- index.js
｜-index.js
｜- index.css

**Comment by KaiHotz** [comment]
@dalongjason I'm sorry but i don't quite understand your question
