### ISSUE TITLE
Error if I want to import a specific component

### ISSUE THREAD

**Issue by t1fmarin** [KaiHotz/react-rollup-boilerplate#40]
Works!!
import { Button } from 'react-rollup-boilerplate'

Get ERROR :(
import { Button } from "react-rollup-boilerplate/button";
import { Button } from "react-rollup-boilerplate/dist/components/button";

The problem that I currently see is that to use a component I must call it from the root but let's say if I have a library of 50 components, if only one button is going to load the entire lib and that is not good for the final bundle. Another little thing that is not clear to me is the issue if the styles are injected into each component, that is, when importing the button, only the button styles are loaded

**Comment by KaiHotz** [comment]
@t1fmarin This should be resolved now.

**Comment by t1fmarin** [comment]
Thanks for listening, I just have a question; that is, does the lib now allow you to export specific components?

**Comment by KaiHotz** [comment]
like i said, this is just a boilerplate to get you started.
If you have the need to export specific components you might want to read about rollup configuration options, and then do the necessary changes in the `rollup.config.mjs` file, specifically in the `input`  option
