### ISSUE TITLE
Can style-components be used instead of CSS?

### ISSUE THREAD

**Issue by brightpixels** [KaiHotz/react-rollup-boilerplate#6]
Can style-components be used instead of CSS?

**Comment by KaiHotz** [comment]
yes you can, you just need to install styled components lib and use it

**Comment by brightpixels** [comment]
Should I install it as peer dependency or bundle it with my library?

**Comment by KaiHotz** [comment]
@brightpixels this is something you must decide on your own. If your library will be used in a project that uses styled components you might add it to devDependencies and  peerDependencies, therefore every body who uses your library needs to install styled components dependencies manually. But then again i don't know what you are going to develop and therefore i can not make those decisions for you.

**Comment by brightpixels** [comment]
My intention is for my project/lib to be used by other apps. I found this useful link on the official styled-components website which answers my question (basically confirming what you said): https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library
